### PR TITLE
feat: integrated virtualenv support

### PR DESCRIPTION
**Pull request by jdx**

### CODE REVIEW

**Comment by joshkaplinsky** [comment]
@jdxcode thanks for maintaining/porting this poetry plugin to rtx! I'm curious what the motivation behind defaulting this venv behavior is? In my opinion, as a user, having a plugin perform any actions (outside of installation) is unexpected for a tool dependency manager. Is this something that could instead be an optional config for the plugin?

**Comment by jdx** [comment]
It is optional

**Comment by joshkaplinsky** [comment]
Thanks for the clarification! It looks like this line is always evaluating to true when `$VIRTUAL_ENV` is an empty string causing the plugin to try an create a new venv each time.  https://github.com/rtx-plugins/rtx-poetry/blob/6e1231e102284e897bd09301065c3ba49fb0bcb5/bin/exec-env#L9 

I'm happy to PR a change, assuming this is the expected behavior.

**Comment by jdx** [comment]
Ah yes, that logic looks backwards. Should be `! -z $VIRTUAL_ENV` I think.

**Comment by jdx** [comment]
I'm a little surprised how something so glaring could slip through though

**Comment by jdx** [comment]
yeah it looks wrong, rtx-python is doing the correct thing here:

https://github.com/rtx-plugins/rtx-python/blob/2b29b1695c110cab5659e2bc568088f6ba0280a7/bin/exec-env#L11

**Comment by jeffcasavant** [comment]
Poetry should be managing the virtual environment per-project, from what I know.  It doesn't make sense to create one globally - it won't get used.  At least that's how I've used Poetry in the past.

**Comment by joshkaplinsky** [comment]
@jdxcode Followup to this, handling the case where the `pyproject` config is not provided in `.rtx.toml`: https://github.com/rtx-plugins/rtx-poetry/pull/2

**Pull request merged**
