### PR TITLE
Use releases to derive version list

### LINKED ISSUE #12: Unreleased version is being considered the latest
Poetry 1.8.3 is unreleased due to some kind of build failure, but because it's tagged it is being considered the latest version since `list-all` uses git tags, leading to this error:

```
$ mise upgrade
curl: (23) Failed writing received data to disk/application
mise ~/.local/share/mise/plugins/poetry/bin/install failed
curl: (23) Failed writing received data to disk/application
Retrieving Poetry metadata

Version 1.8.3 does not exist.

Cleanup: Something went wrong!

47 /Users/josh/.local/share/mise/plugins/poetry/bin/install: POETRY_HOME=$install_path python3 - --version "$version" $flags
mise ~/.local/share/mise/plugins/poetry/bin/install exited with non-zero status: exit code 1
mise Run with --verbose or MISE_VERBOSE=1 for more information
```

I'll make a PR shortly :)

### PR DESCRIPTION
**Pull request by joshbode**
Fixes #12

### CODE REVIEW

**Comment by joshbode** [comment]
Looks like build is failing because the mise action is still trying to pull in the unreleased version

**Comment by jdx** [comment]
This needs to respect the GitHub api token if it's set, try to see if you can find a reference from a different plugin

**Comment by joshbode** [comment]
> This needs to respect the GitHub api token if it's set, try to see if you can find a reference from a different plugin

Done - saw that in another plugin but didn't realise it was universal and left it out :)

**Comment by joshbode** [comment]
Thanks @jdx :)

**Pull request merged**
